# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Send timers

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Send timers'
        # Default value if no value is explicitly provided
        default: 'Send timers'
        # Input has to be provided for the workflow to run
        required: true
# Summer time: 10:00
# Winter time 9:00
env:
  WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}
  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
  
jobs:
  bot:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: node app.js
